# Generated by Django 5.2.10 on 2026-01-19 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0003_coaching_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DUDUK', '두둑 챌린지'), ('EVENT', '이벤트 챌린지')], default='DUDUK', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('icon_color', models.CharField(blank=True, default='#6366F1', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('EASY', '쉬움'), ('MEDIUM', '보통'), ('HARD', '어려움')], default='MEDIUM', max_length=20)),
                ('keyword', models.CharField(blank=True, choices=[('TOP_SAVING', '최고 절약'), ('POPULAR_SUCCESS', '인기 성공'), ('MANY_FAIL', '다수 실패')], max_length=50)),
                ('duration_days', models.IntegerField(default=7)),
                ('target_amount', models.IntegerField(blank=True, null=True)),
                ('target_category', models.CharField(blank=True, max_length=50)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '챌린지',
                'verbose_name_plural': '챌린지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='sparkles', max_length=50)),
                ('icon_color', models.CharField(blank=True, default='#8B5CF6', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('EASY', '쉬움'), ('MEDIUM', '보통'), ('HARD', '어려움')], default='MEDIUM', max_length=20)),
                ('duration_days', models.IntegerField(default=7)),
                ('target_amount', models.IntegerField(blank=True, null=True)),
                ('target_category', models.CharField(blank=True, max_length=50)),
                ('is_started', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_challenges', to='coaching.coaching')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 맞춤 챌린지',
                'verbose_name_plural': 'AI 맞춤 챌린지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행 중'), ('SUCCESS', '성공'), ('FAILED', '실패'), ('CANCELLED', '취소')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_amount', models.IntegerField(default=0)),
                ('current_spent', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_challenges', to='challenges.aigeneratedchallenge')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 챌린지',
                'verbose_name_plural': '사용자 챌린지 목록',
                'ordering': ['-started_at'],
            },
        ),
    ]
