# Generated by Django 5.2.8 on 2026-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigeneratedchallenge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
