# Generated by Django 5.2.10 on 2026-01-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_aigeneratedchallenge_updated_at'),
        ('challenges', '0004_migrate_ai_challenges_data'),  # 데이터 마이그레이션 먼저 실행
        ('coaching', '0004_coaching_estimated_savings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallenge',
            name='ai_challenge',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='type',
        ),
        migrations.AddField(
            model_name='challenge',
            name='coaching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_challenges', to='coaching.coaching'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='source',
            field=models.CharField(choices=[('DUDUK', '두둑 챌린지'), ('EVENT', '이벤트 챌린지'), ('AI', 'AI 맞춤 챌린지')], default='DUDUK', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='icon',
            field=models.CharField(blank=True, default='sparkles', max_length=50),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge'),
        ),
        migrations.DeleteModel(
            name='AIGeneratedChallenge',
        ),
    ]
