# Generated by Django 5.2.10 on 2026-01-23 13:30

from django.db import migrations


def migrate_ai_challenges_to_challenges(apps, schema_editor):
    """
    AIGeneratedChallenge 데이터를 Challenge로 이전하고
    UserChallenge의 ai_challenge를 challenge로 매핑
    """
    # 마이그레이션 0003 실행 전 상태의 모델 가져오기
    AIGeneratedChallenge = apps.get_model('challenges', 'AIGeneratedChallenge')
    Challenge = apps.get_model('challenges', 'Challenge')
    UserChallenge = apps.get_model('challenges', 'UserChallenge')
    
    # 1. 기존 type을 source로 변환
    for challenge in Challenge.objects.all():
        # type 필드가 아직 있다면 source로 복사
        if hasattr(challenge, 'type'):
            challenge.source = challenge.type
            challenge.save()
    
    # 2. AIGeneratedChallenge를 Challenge로 복사
    ai_challenge_mapping = {}  # old_ai_challenge_id -> new_challenge_id
    
    for ai_challenge in AIGeneratedChallenge.objects.all():
        new_challenge = Challenge.objects.create(
            source='AI',
            name=ai_challenge.name,
            description=ai_challenge.description,
            icon=ai_challenge.icon,
            icon_color=ai_challenge.icon_color,
            points=ai_challenge.points,
            difficulty=ai_challenge.difficulty,
            duration_days=ai_challenge.duration_days,
            target_amount=ai_challenge.target_amount,
            target_category=ai_challenge.target_category,
            user=ai_challenge.user,
            coaching=ai_challenge.coaching,
            is_active=ai_challenge.is_active,
            created_at=ai_challenge.created_at,
            updated_at=ai_challenge.updated_at
        )
        ai_challenge_mapping[ai_challenge.id] = new_challenge.id
    
    # 3. UserChallenge의 ai_challenge를 challenge로 매핑
    for user_challenge in UserChallenge.objects.all():
        if hasattr(user_challenge, 'ai_challenge_id') and user_challenge.ai_challenge_id:
            # ai_challenge가 있는 경우 해당하는 새 challenge로 매핑
            new_challenge_id = ai_challenge_mapping.get(user_challenge.ai_challenge_id)
            if new_challenge_id:
                user_challenge.challenge_id = new_challenge_id
                user_challenge.save()


def reverse_migration(apps, schema_editor):
    """
    역방향 마이그레이션 (롤백 시)
    주의: 데이터 손실 가능성 있음
    """
    Challenge = apps.get_model('challenges', 'Challenge')
    # AI 챌린지 삭제 (롤백 시)
    Challenge.objects.filter(source='AI').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_aigeneratedchallenge_updated_at'),
    ]

    operations = [
        migrations.RunPython(migrate_ai_challenges_to_challenges, reverse_migration),
    ]
