# Generated by Django 5.2.10 on 2026-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_userchallenge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengetemplate',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='challengetemplate',
            name='icon_color',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='icon_color',
        ),
        migrations.AlterField(
            model_name='challengetemplate',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='normal', max_length=10, verbose_name='난이도'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='normal', max_length=10, verbose_name='난이도'),
        ),
    ]
