# Generated by Django 5.2.10 on 2026-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_remove_challengetemplate_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일시'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작일시'),
        ),
    ]
