# Generated by Django 5.2.11 on 2026-02-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_challengetemplate_success_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('saved', '저장됨'), ('ready', '시작 대기'), ('active', '진행 중'), ('completed', '완료'), ('failed', '실패')], default='active', max_length=20, verbose_name='상태'),
        ),
    ]
