# Generated by Django 5.2.11 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("COACHING", "코칭 생성"),
                    ("MONTHLY_REPORT", "월간 리포트 생성"),
                    ("CHALLENGE", "챌린지"),
                    ("BATTLE", "윤택지수 대결"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="notification",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
