# Generated by Django 5.2.8 on 2026-01-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_has_children_user_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.IntegerField(default=0),
        ),
    ]
