# Generated by Django 5.2.10 on 2026-01-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='프로필 완성 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='월 예산'),
        ),
        migrations.AddField(
            model_name='user',
            name='spending_to_improve',
            field=models.TextField(blank=True, null=True, verbose_name='개선하고 싶은 소비'),
        ),
    ]
