# Generated by Django 5.2.10 on 2026-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_age_user_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='캐릭터 이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='character_type',
            field=models.CharField(choices=[('char_cat', '두둑이(고양이)'), ('char_dog', '두둑이(강아지)'), ('char_ham', '두둑이(햄스터)'), ('char_sheep', '두둑이(양)')], default='char_cat', max_length=20, verbose_name='캐릭터 타입'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='현재 포인트'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points_earned',
            field=models.IntegerField(default=0, verbose_name='총 적립 포인트'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points_used',
            field=models.IntegerField(default=0, verbose_name='총 사용 포인트'),
        ),
    ]
