# Generated by Django 5.2.11 on 2026-02-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopitem_image_key'),
        ('users', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipped_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_background', to='shop.shopitem', verbose_name='착용 중인 배경'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipped_clothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_clothing', to='shop.shopitem', verbose_name='착용 중인 의상'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipped_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_item', to='shop.shopitem', verbose_name='착용 중인 아이템'),
        ),
    ]
