# Generated by Django 5.2.11 on 2026-02-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_equipped_background_user_equipped_clothing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='equipped_background',
        ),
        migrations.RemoveField(
            model_name='user',
            name='equipped_clothing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='equipped_item',
        ),
    ]
