# Generated by Django 5.2.8 on 2026-02-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_auth_provider_user_social_id"),
        ("users", "0008_remove_user_equipped_background_and_more"),
    ]

    operations = []
