# Generated by Django 5.2.11 on 2026-02-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_monthlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='report_content',
            field=models.JSONField(default=dict, verbose_name='리포트 내용'),
        ),
    ]
