# Generated by Django 5.2.8 on 2026-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0003_coaching_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="coaching",
            name="estimated_savings",
            field=models.IntegerField(default=0),
        ),
    ]
