# Generated by Django 5.2.10 on 2026-03-24 00:00

from django.db import migrations, models


def backfill_generated_challenge_flag(apps, schema_editor):
    Coaching = apps.get_model('coaching', 'Coaching')
    UserChallenge = apps.get_model('challenges', 'UserChallenge')

    coaching_ids = UserChallenge.objects.filter(
        source_coaching__isnull=False,
    ).values_list('source_coaching_id', flat=True).distinct()

    Coaching.objects.filter(id__in=coaching_ids).update(has_generated_challenge=True)


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_userchallenge_attempt_grouping'),
        ('coaching', '0006_coaching_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='has_generated_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_generated_challenge_flag, migrations.RunPython.noop),
    ]
