# Generated by Django 5.2.11 on 2026-02-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='이미지 조합 키'),
        ),
    ]
