# Generated by Django 5.2.12 on 2026-03-23 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': '챗봇 메시지', 'verbose_name_plural': '챗봇 메시지 목록'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': '챗봇 세션', 'verbose_name_plural': '챗봇 세션 목록'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='메시지 본문'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='메시지 기록 시간'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', '사용자'), ('assistant', '두두(AI)')], help_text='메시지 작성자 (user 또는 assistant)', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(help_text='소속된 대화 세션', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='세션 생성 시간'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='마지막 대화 발생 시간'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(help_text='대화를 진행 중인 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
